### ISSUE TITLE
Weird bug if first artist in .scrobbler.log starts with 'S'

### ISSUE THREAD

**Issue by frpst** [ultraelephant/pyapplier#1]
The program usually works well but today I got the error message "local variable 'artist' referenced before assignment" after typing 'Yes'.  I checked the code for 'artist' and found a mention of it in line 90 within a boolean of some kind of check of weather the line starts with 'S'. I tried manually moving an artist that doesn't start with 'S' to the top of the log and then it worked as it usually do.

**Comment by ultraelephant** [comment]
Hi, Thank you for report.

Could you please give me an example of scrobbler.log

**Comment by frpst** [comment]
Sorry for late answer. Here is a new log with the same issue (My theory seems to have been wrong):

[.scrobbler.log](https://github.com/ultraelephant/pyapplier/files/5503693/default.scrobbler.log)

**Comment by ultraelephant** [comment]
Thank you. I've fixed it in https://github.com/ultraelephant/pyapplier/releases/tag/0.0.4
